name: Dump Context

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: utenx/gh-dump-context@v1
        with:
          context: github